[project]
name = seline_read
description = An app for Zlibrary, build by CJMP.
type = app
organization = liquid.studio

# You can add other keels logic-module or module project as dependencies.
# [dependencies]
# packageName = /path/to/logic-module
# moduleName = /path/to/module
